server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: servicio-items
          uri: lb://servicio-items
          predicates:
            - Path=/items/**
        - id: servicio-productos
          uri: lb://servicio-productos
          predicates:
            - Path=/productos/**
        - id: servicio-recomendaciones
          uri: lb://servicio-recomendaciones
          predicates:
            - Path=/recomendaciones/**
